# Site settings
title: Chronicles of a Junior Dev
email:
description:
baseurl: "/chronicles" # the subpath of your site, e.g. /blog/
url: "http://alainakafkes.github.io" # the base hostname & protocol for your site
twitter_username: alainakafkes
github_username: alainakafkes

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
